apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 30080  # You can choose a port between 30000–32767


#type: ClusterIP # Default. Only accessible from within the cluster.
# type: NodePort # Uncomment this if you want to access it from outside your cluster via a node's IP
  
